name: ltogt_utils_flutter
description: A collection of utility widgets, helpers, ... for flutter
version: 0.0.1
homepage: https://github.com/ltOgt
publish_to: none

environment:
  sdk: ">=2.18.0-0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  ltogt_utils:
    git: git@github.com:ltOgt/ltogt_utils.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
